### PR TITLE
Temp Radium example

### PR DESCRIPTION
**Pull request by MaxSvargal**
Miss pull request, sorry.

### CODE REVIEW

**Comment by iam4x** [comment]
Nice! It's nice to have an example with radium, do you have so code clean to do? I would like to publish this as another branch to give people the choice :+1:

**Comment by MaxSvargal** [comment]
@iam4x yes i can prepared a pull request later

**Comment by jaredkotoff** [comment]
Yea I would like to see this merged and working clean with the lasted master so I could try to switch to Radium. css files are just a mess and becoming hard to maintain when I have almost 50 components.  
I've wanted to switch after seeing this presentation https://speakerdeck.com/chantastic/styling-react-components

**Comment by MaxSvargal** [comment]
@jaredkotoff https://github.com/iam4x/isomorphic-flux-boilerplate/pull/225

**Comment by MaxSvargal** [comment]
Move to #225

**Pull request closed without merging**
