### PR TITLE
Updates the koa-helmet library

### PR DESCRIPTION
**Pull request by dangerdespain**
Hi Max, I'm starting my flux development here with your boilerplate! Thanks for putting this together!

I had a few bumps with setup using your instructions. `nvm install stable` is currently resolving to node v5.3.0) The v1.0.0-alpha koa-helmet library is still using generators while the v2.0.0-alpha is converted to promises. I scanned through the changelog and made code updates where appropriate. A peer dependency (history package) was also updated.

I'm also submitting a separate pull request with a simpler patch using the koa-convert library to convert koa-helmet. Either PR should result in a running server but this is the more 'correct' fix in my opinion.

### CODE REVIEW

**Comment by dangerdespain** [comment]
P.S. here is the exception that led me to this PR

    TypeError: Support for generators has been removed. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa#example-with-old-signature
    at Application.use (/Users/ddespain/sites/isomorphic-flux-boilerplate/node_modules/koa/lib/application.js:104:40)
    at Object.<anonymous> (/Users/ddespain/sites/isomorphic-flux-boilerplate/server/koa.js:25:5)
    at Module._compile (module.js:398:26)
    at normalLoader (/Users/ddespain/sites/isomorphic-flux-boilerplate/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ddespain/sites/isomorphic-flux-boilerplate/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/ddespain/sites/isomorphic-flux-boilerplate/server/index.js:17:1)
    at Module._compile (module.js:398:26)
    at normalLoader (/Users/ddespain/sites/isomorphic-flux-boilerplate/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/ddespain/sites/isomorphic-flux-boilerplate/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

**Comment by iam4x** [comment]
Hello @dangerdespain, thank's for the contribution.

Could you remove the changes of `history` module and I'll be good to merge the PR :+1:

**Comment by dangerdespain** [comment]
"A peer dependency (history package) was also updated."

history@1.13.x ->1.17.x was the dependency :) The other pull request would be more appropriate if there's a reason that the history package shouldn't be updated.

**Comment by iam4x** [comment]
We didn't updated history because it throws warnings and flood the console. See https://github.com/iam4x/isomorphic-flux-boilerplate/issues/164

**Comment by dangerdespain** [comment]
Then this PR is probably stuck. Hmm.. #186 would be the easier resolution if you'd like to check that out and re-open it. There are no dependency changes.

**Comment by iam4x** [comment]
@dangerdespain Or you can just `npm i -S koa-helmet@2.0.0-alpha.1` without the history module changes :+1:

**Comment by jaredkotoff** [comment]
@iam4x I actually included koa-helmet update in #199

**Pull request closed without merging**
