### PR TITLE
disable displayName in eslint

### PR DESCRIPTION
**Pull request by tsm91**
[disable displayName in eslint](https://github.com/yannickcr/eslint-plugin-react/blob/59ac136af48be4a5e746e7ee292fc452963147a8/docs/rules/display-name.md), since we are using JSX syntax and this is automatically fixed

### CODE REVIEW

**Comment by iam4x** [comment]
@tsm91 How `displayName` is setted with JSX? It takes the name of the class?

**Comment by tsm91** [comment]
Exactly, if you have react-devtools installed you can test it very fast, the component name is always the name of your class.

**Comment by iam4x** [comment]
Ok nice find, didn't found any information about this.

**Comment by tsm91** [comment]
check this: https://facebook.github.io/react/docs/jsx-in-depth.html#the-transform

also https://babeljs.io/docs/usage/jsx/#additional-changes I also checked with `export default class Something extends React.Component ..` but `displayName` will be the name of the class and not the filename

**Comment by iam4x** [comment]
@tsm91 Thank's for references.

**Pull request merged**
