### PR TITLE
Add react intl

### PR DESCRIPTION
**Pull request by iam4x**
Implementation of [react-intl](https://github.com/yahoo/react-intl)

- [x] Implement `react-intl` client logic
- [x] Implement `react-intl` server logic
- [x] Switch locale
- [x] Split translations into chunks for lazy-loading
- [x] Add Spinner on changing lang req
- [x] Persist locale into `cookie` / `localstorage`
- [x] Clean the warnings from `react-a11y`
- [x] Fix actual tests
- [x] Add tests for `react-intl`
- [x] Fix different markup client / server
- [x] Fix `.json` webpack chunks
- [x] Update README

### CODE REVIEW

**Comment by iam4x** [comment]
It fixes also #14

**Comment by dmitry** [comment]
Thank you for working on that!

Do you know some service, that helps to translate the keys and then export them into the intl format?
In our current projects I'm using webtranslateit.com and phraseapp.com, but they are not providing such export.
What kind of the workflow do you use to translate application when using `intl`?

**Comment by iam4x** [comment]
@dmitry I haven't used such services yet, what is output from them? a JSON / YAML ?

**Comment by dmitry** [comment]
JSON or YAML can be exported. I know that it's easy to convert JSON/YAML to

```json
{
  messages: JSON
}
```

But still. Anyway thank you for the answer!

**Comment by iam4x** [comment]
@dmitry You can have a script run before compiling for production or/and at first compilation on dev, look how I call `webpack/utils/clean-dist.js` into `webpack/prod.config.js`

It shouldn't be a big deal :+1:

**Pull request merged**
