### PR TITLE
PWA - take 2

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Hi @iam4x 

Finally had time to rebase on latest, closed older pulls as i was unable to fix the branches :/

~~~ Notes from OLD PR ~~~
Service worker can be tested on localhost in chrome without https. Just make sure to access website with localhost[:port] or 127.0.0.1[:port].
Source: https://www.chromium.org/blink/serviceworker/service-worker-faq

Also i have added a "start" script to use zeit's $ now for example to deploy the app.
Production build doesn't generate map files for js anymore.

### CODE REVIEW

**Comment by iam4x** [comment]
Can you add a note on the README.md explaining the meaning of PWA and how is it achieved? And it will be good to merge 👍

**Comment by EugeneHlushko** [comment]
@iam4x can you double check if it makes sense now?

**Comment by EugeneHlushko** [comment]
@iam4x ill merge this in if there is nothing we can add here over the weekend. Would like to migrate to webpack 2 after these changes are in.

**Comment by iam4x** [comment]
💯

**Pull request merged**
