### PR TITLE
change binds to arrow funcs

### PR DESCRIPTION
**Pull request by EugeneHlushko**
See how it is converted under the hood: https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=class%20PostInfo%20extends%20React.Component%20%7B%0A%09handleOptionsButtonClick%20%3D%20(e)%20%3D%3E%20%7B%0A%20%20%20%20this.setState(%7BshowOptionsModal%3A%20true%7D)%3B%0A%20%20%7D%0A%7D

### CODE REVIEW

**Comment by dmitry** [comment]
Looks nicer! :+1:

**Comment by iam4x** [comment]
This is only code style preferences, why should I change this?

**Comment by EugeneHlushko** [comment]
@iam4x It really just looks nicer and readable, if you don't think so just reject this

**Comment by iam4x** [comment]
@EugeneHlushko I would like to build a community around the boilerplate, so if the users prefer this syntax and it makes more sense I'll go for it :+1:

**Comment by dmitry** [comment]
@iam4x :+1:

**Comment by adamjv90** [comment]
:+1:

**Pull request merged**
