### PR TITLE
refactor: use alt-resolver as class

### PR DESCRIPTION
**Pull request by doodledood**
Use alt-resolver as class.
This solves #28 as a side product, and looks a bit cleaner in my perspective.
Plus, I think cleanPromises is now not really needed, am I correct?

### CODE REVIEW

**Comment by iam4x** [comment]
Thank's @doodledood, it's perfect. And yes I agree we don't need `cleanPromises` anymore.

I'll fix tests on master, and you will be abble to rebuild for merging the PR :+1:

**Comment by iam4x** [comment]
You can rebase on master @doodledood

**Comment by MrOrz** [comment]
:+1:

**Comment by iam4x** [comment]
Two last things, let's remove `cleanPromises()` and update the `README.md` with the new syntax. (Or want me to do it?)

Thank's for the work @doodledood

**Comment by doodledood** [comment]
Go ahead and do it, I will try to make another example using inline css :) #25

**Pull request merged**
