### PR TITLE
allow auth on server side

### PR DESCRIPTION
**Pull request by AllenFang**
Thanks provide #161 for authorization. But if login successful and redirect to /account, then reload /account will cause a unauthorized process and redirect to /login. So fix this issue by adding auth token in cookie and populate to session store on server side

### CODE REVIEW

**Comment by AllenFang** [comment]
--update--  fix #163  and #164

**Comment by jaredkotoff** [comment]
I actually already tried to use history v1.16.0. Were you able to repoduce and solve my issues by using 1.13.x?

**Comment by AllenFang** [comment]
@jaredkotoff, yes

**Comment by iam4x** [comment]
Thank's :)

**Pull request merged**
