### PR TITLE
Flowtype

### PR DESCRIPTION
**Pull request by iam4x**
#26

### CODE REVIEW

**Comment by doodledood** [comment]
great :)
you might want to use the flag '?stripTypes', so the type checking only happens staticly and reduce the overhead in production

**Comment by doodledood** [comment]
[From README.md](https://github.com/gaearon/flowcheck-loader/blob/master/README.md)

**Comment by iam4x** [comment]
@doodledood `?stripTypes` is for `jsx-loader`, as I don't use the `flowcheck-loader` on production config it shouldn't be checking on production.

**Comment by doodledood** [comment]
oh I see, my bad

**Pull request merged**
