### PR TITLE
Large Project Reorganize

### PR DESCRIPTION
**Pull request by jaredcat**
You might want to make this its own branch so people have a choice. 
The current organization of files is good for smaller projects but I have built a very large application on this boilerplate and have found that the CSS is hard to manage when it's separated from its components. 
In the Reactiflux Discord channle. It was suggested to group components with their resources.  

Inline CSS or radium might be even better for styling management, but I plan to switch to this layout for now.  
Let me know if you have any comments or ideas about further organization.

### CODE REVIEW

**Comment by utkuturunc** [comment]
I am using a similar approach but I don't like:
```
import Header from 'components/header/header';
```

As a workaround, I named all component files to index.jsx.

Maybe a package.json for each component can be created. But it would be an inconvenience without yeoman.

**Comment by jaredkotoff** [comment]
@utkuturunc right, I read about the index.jsx thing [here] (http://reactjsnews.com/structuring-react-projects/) after I made this. I'll probably make another commit for that.

**Comment by utkuturunc** [comment]
@jaredkotoff Keep in mind that text editors (at least atom) show 'index.jsx' at all tabs. It becomes annoying if you have a lot of tabs open at the same time. My project at this point is too big to do anything about it.

My 2 solutions are:
- Name the file componentName.jsx. Add a package.json with main: 'componentName.jsx'
- Name the file componentName.jsx. Add an index.jsx file that imports and exports the component.

I am slowly migrating to the second solution. It lets me do things like:

```
import { Input, TextArea } from 'components/FormFields
```

**Comment by iam4x** [comment]
screen shot 2016-02-25 at 23 48 04

This is how I do on big projects, I keep the same structure into `app/components` and `app/styles`. I never have been a big fan of small components with styles inside it as-well, certainly because of my RoR background.

But I'm open to merge it into another branch, and publish a note on the README.md :+1:

**Comment by jaredkotoff** [comment]
@iam4x I had thought about that layout. but it doesn't seem like much of an improvement to me. Still lots of expanding folders. If I expand components and then styles its a lot of scrolling to find the corresponding files. I've been using the new layout for about a week and I'm enjoying opening one folder to find both the component and styling at the same time.  
Of course, everyone's going to have their own opinion but this layout just makes sense to me.  
I'll add the index.js files like utkuturunc suggested and merge in the new changes you just pushed soon.

**Comment by iam4x** [comment]
Exactly, I dont open folders much, I use CMD+P to go to file into Atom. I just type `styles xxxx` or `comp xxx` and works great for me.

Waiting for your rebase :+1:

**Comment by utkuturunc** [comment]
@iam4x I move components around several projects. If a component is contained completely in a single folder it makes it really easy to copy it around.

By the way which theme are you using?

**Pull request closed without merging**
