### PR TITLE
Further enhancements for babel 6 compatability

### PR DESCRIPTION
**Pull request by btomasini**
This PR is a continuation of existing attempts to make the project work with Babel 6.  Additional changes include:

* Compatibility with more recent version of Babel
* Karma tests

One of the unit tests fails accessing messages.users.title property path. Not knowing enough about the inner workings of the project, I was unable to fix it.

### CODE REVIEW

**Comment by btomasini** [comment]
In one commit I converted from Firefox to Chrome.  I reverted this change in a more recent commit.

**Comment by iam4x** [comment]
:tada: Thank's for the hard work! I'm going to review and test that :+1:

One of the major problems of babel6 it's doesn't support older browsers like IE8 / IE9 and that's why I didn't gave it another shot since I need to support these browsers on some projects.

I'm going to try all of that with https://github.com/sorrycc/es3ify-loader ;)

**Comment by MaxSvargal** [comment]
@btomasini use `babel-plugin-add-module-exports` which fix the default exporting.

**Comment by iam4x** [comment]
closed for #136

**Pull request closed without merging**
