### PR TITLE
Upgrade webpack to version 2+

### PR DESCRIPTION
**Pull request by EugeneHlushko**

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
This is a WIP, will see to it during few more days. Already seems to be working

**Comment by iam4x** [comment]
Thank's for all the contributions @EugeneHlushko

**Comment by EugeneHlushko** [comment]
Glad i can help, once this boilerplate saved me some hours of set up, time to give it back! 💃

**Comment by EugeneHlushko** [comment]
Still need to look at few warnings and few errors in dev mode, though they were occurring in with webpack1 too

**Comment by EugeneHlushko** [comment]
@iam4x im done here, i'll leave it open for a couple of days in case you want to change/contribute

**Review by iam4x — APPROVED** [review]

**Comment by EugeneHlushko** [comment]
That was prompt, merging in

**Pull request merged**
