### PR TITLE
Add service worker setup

### PR DESCRIPTION
**Pull request by EugeneHlushko**
Hi @iam4x 
Still trying to verify if its working as expected, need HTTPS enabled address to confirm.
Also i have added a "start" script to use zeit's `$ now` for example to deploy the app.
Production build doesn't generate map files for js anymore.

### CODE REVIEW

**Comment by EugeneHlushko** [comment]
UPDATE:
Service worker can be tested on localhost in chrome without https. Just make sure to access website with localhost[:port] or 127.0.0.1[:port].
Source: https://www.chromium.org/blink/serviceworker/service-worker-faq

@iam4x would be nice to hear your thoughts on this, its working now

**Comment by EugeneHlushko** [comment]
No problems @iam4x i've done this as a preparation for my SW talk

**Comment by EugeneHlushko** [comment]
@iam4x any luck looking into this? Think people benefit from it anyhow if use the BP

**Comment by iam4x** [comment]
Totally forgot, will look into it. We are implement service workers here at work also. cc @MayasHaddad

**Comment by MayasHaddad** [comment]
Hello @EugeneHlushko 

I cloned your fork and ran `npm start` 

I'm having this error at sw registration:
```
Uncaught (in promise) TypeError: Failed to register a ServiceWorker: An unknown error occurred when fetching the script.
```

Weirdly, the file is perfectly accessible:
lqfadhfu6z

Any clue? 🙏

**Comment by EugeneHlushko** [comment]
Hi @MayasHaddad didnt know about this issue too, never faced actually.

**Comment by iam4x** [comment]
@EugeneHlushko It's good to merge, can you rebase on master? 👍

**Comment by EugeneHlushko** [comment]
@iam4x Yeah will do after work :)

**Pull request closed without merging**
